# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-02 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='friend',
            field=models.ManyToManyField(to='database.Account'),
        ),
    ]
