# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20190402_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Account'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_order',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
