# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-15 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20190412_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='artical',
            new_name='article',
        ),
    ]
