# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20190415_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='retry',
            field=models.ManyToManyField(to='database.Comment'),
        ),
    ]
